#!/bin/sh

echo_help()
{
  echo "Usage: $0 [options...]"
  echo "    -n    Specify NDK root path for the build."
  echo "    -a    Select target API level."
  echo "    -t    Select target architectures."
  echo "          Android supports the following architectures: armeabi armeabi-v7a arm64-v8a x86 x86_64."
  echo "    -o    Select OpenSSL (1.1.1 series) version. E.g. 1.1.1h"
  echo "    -s    Select a specific SRT tag. E.g. v1.4.3"
  echo
  echo "Example: ./build-android -n /home/username/Android/Sdk/ndk/21.4.7075529 -a 28 -t \"armeabi-v7a arm64-v8a x86 x86_64\" -o 1.1.1h -s v1.4.3"
  echo
}

# Init optional command line vars
NDK_ROOT=""
API_LEVEL=28
BUILD_TARGETS="armeabi armeabi-v7a arm64-v8a x86 x86_64"
OPENSSL_VERSION=1.1.1h
SRT_VERSION=""

while getopts n:a:t:o:s: option
do
 case "${option}"
 in
 n) NDK_ROOT=${OPTARG};;
 a) API_LEVEL=${OPTARG};;
 t) BUILD_TARGETS=${OPTARG};;
 o) OPENSSL_VERSION=${OPTARG};;
 s) SRT_VERSION=${OPTARG};;
 *) twentytwo=${OPTARG};;
 esac
done

echo_help

if [ -z "$NDK_ROOT" ] ; then
 echo "NDK directory not set."
 exit 128
else
 if [ ! -d "$NDK_ROOT" ]; then
  echo "NDK directory does not exist: $NDK_ROOT"
  exit 128
 fi
fi

# Determine the path of the executing script
BASE_DIR=$(readlink -f $0 | xargs dirname)

$BASE_DIR/mkssl -n $NDK_ROOT -a $API_LEVEL -t "$BUILD_TARGETS" -o $OPENSSL_VERSION

if [ ! -d $BASE_DIR/srt ]; then
 git clone https://github.com/Haivision/srt srt
 if [ ! -z "$SRT_VERSION" ]; then
  git -C $BASE_DIR/srt checkout $SRT_VERSION
 fi
fi

JNI_DIR=$BASE_DIR/prebuilt

for build_target in $BUILD_TARGETS; do
 git -C $BASE_DIR/srt clean -fd
 $BASE_DIR/mksrt -n $NDK_ROOT -a $API_LEVEL -t $build_target -s $BASE_DIR/srt -i $BASE_DIR/$build_target

 mkdir -p $JNI_DIR/$build_target
 cp $BASE_DIR/$build_target/lib/libsrt.so $JNI_DIR/$build_target/libsrt.so
done
