#!/bin/sh

while getopts s:i:t:n:a: option
do
 case "${option}"
 in
 s) SRC_DIR=${OPTARG};;
 i) INSTALL_DIR=${OPTARG};;
 t) ARCH_ABI=${OPTARG};;
 n) NDK_ROOT=${OPTARG};;
 a) API_LEVEL=${OPTARG};;
 *) twentytwo=${OPTARG};;
 esac
done


cd $SRC_DIR
./configure --use-openssl-pc=OFF --OPENSSL_USE_STATIC_LIBS=true \
--CMAKE_PREFIX_PATH=$INSTALL_DIR --CMAKE_INSTALL_PREFIX=$INSTALL_DIR --CMAKE_ANDROID_NDK=$NDK_ROOT \
--CMAKE_SYSTEM_NAME=Android --CMAKE_SYSTEM_VERSION=$API_LEVEL --CMAKE_ANDROID_ARCH_ABI=$ARCH_ABI \
--CMAKE_C_FLAGS="-fPIC" --CMAKE_SHARED_LINKER_FLAGS="-Wl,--build-id" \
--enable-c++11 --enable-stdcxx-sync \
--enable-debug=2 --enable-logging=0 --enable-heavy-logging=0 --enable-apps=0
make
make install
