#!/bin/bash
# Now Check if Tcl is installed, run it if so. The backslash extends the comment and hides the line below against Tcl interpreter \
exec tclsh "$0" "$@" || echo "Please install 'tcl' package first - it's required to run any other scripts here." && exit 1

# 
# SRT - Secure, Reliable, Transport
# Copyright (c) 2017 Haivision Systems Inc.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; If not, see <http://www.gnu.org/licenses/>
# 

if { [catch {package require Tcl 8.5}] } {
	puts stderr "Tcl version at least 8.5 required, please upgrade"
	exit 1
}

set ok 1

if { [catch {exec pkg-config --exists openssl}] } {
	set ok 0
	puts "Openssl: NOT INSTALLED, please install (libssl-dev\[el\], openssl-dev\[el\] etc.)"
} else {
	puts "Openssl: found version [exec pkg-config --modversion openssl] -- ok"
}


set nothave [catch {set cmake [exec cmake --version]}]

if { $nothave } {
	puts "CMake version >= 2.8 required - please install cmake"
	set ok 0
} else {
	set cmakel1 [lindex [split $cmake \n] 0]
	set cv [lindex $cmakel1 end]
	if { [package vcompare $cv 2.8] == -1 } {
		puts "CMake version >= 2.8 required - please upgrade cmake"
		set ok 0
	} else {
		puts "Cmake version $cv -- ok."
	}
}


# May others also apply

if { $ok } {
	puts "All dependencies satisfied, you should be good to go."
	exit 0
}

puts "Please fix the above findings before compiling"
exit 1


