#!/bin/bash
# Now Check if Tcl is installed, run it if so. The backslash extends the comment and hides the line below against Tcl interpreter \
exec tclsh "$0" "$@" || echo "Please install 'tcl' package first - it's required to run any other scripts here." && exit 1

#
# SRT - Secure, Reliable, Transport
# Copyright (c) 2018 Haivision Systems Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

set ok 1

set nothave [catch {set cmake [exec cmake --version]}]

if { $nothave } {
	puts "CMake version >= 2.6 required - please install cmake"
	set ok 0
} else {
	set cmakel1 [lindex [split $cmake \n] 0]
	set cv [lindex $cmakel1 end]
	if { [package vcompare $cv 2.6] == -1 } {
		puts "CMake version >= 2.6 required - please upgrade cmake"
		set ok 0
	} else {
		puts "Cmake version $cv -- ok."
	}
}

set nothave [catch {exec pkg-config --exists libcrypto}]

if { $nothave } {
	puts "Required libcrypto to compile SRT (usually libopenssl-devel package)"
	set ok 0
}


# May others also apply

if { $ok } {
	puts "All dependencies satisfied, you should be good to go."
	exit 0
}

puts "Please fix the above findings before compiling"
exit 1


