name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: NDK-R23
    runs-on: ubuntu-20.04

    steps:
    - name: Setup Android NDK R23
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23
        add-to-path: false
    - uses: actions/checkout@v3
    - name: build
      run: |
        cd ./scripts/build-android/
        echo ${{ steps.setup-ndk.outputs.ndk-path }}
        source ./build-android -n ${{ steps.setup-ndk.outputs.ndk-path }}
