name: Linux

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
    types: [opened, synchronize, reopened]
jobs:
  build:
    strategy:
      matrix:
        crypto: [OFF, openssl, openssl-evp, gnutls, mbedtls, botan]

    name: Build Crypto=${{ matrix.crypto }} C++11
    runs-on: [ubuntu-latest, ubuntu-slim, ubuntu-24.04-arm]
    steps:
    - uses: actions/checkout@v3
    - name: Configure packages and system
      run: |
        sudo apt install -y tcl cmake libssl-dev libgnutls28-dev libmbedtls-dev libbotan-2-dev gdb
        echo "core.%e" | sudo tee /proc/sys/kernel/core_pattern
    - name: Configure
      run: |
        mkdir _build && cd _build
        if [[ ${{ matrix.crypto }} != OFF ]]; then CRYPTO_OPTIONS=-DUSE_ENCLIB=${{ matrix.crypto }}; else CRYPTO_OPTIONS=-DENABLE_ENCRYPTION=OFF; fi
        cmake ../ -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DUSE_CXX_STD=11 -DENABLE_STDCXX_SYNC=ON $CRYPTO_OPTIONS -DENABLE_UNITTESTS=ON -DENABLE_BONDING=ON -DENABLE_HEAVY_LOGGING=ON  -DENABLE_TESTING=ON -DENABLE_EXAMPLES=ON -DENABLE_CODE_COVERAGE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: Build
      run: cd _build && make -j -k
    - name: test
      run: |
        ulimit -c unlimited
        cd _build && ctest --extra-verbose
        SUCCESS=$?
        if [ -f core.test-srt ]; then gdb -batch ./test-srt -c core -ex bt -ex "info thread" -ex quit; else echo "NO CORE - NO CRY!"; fi;
        test $SUCCESS == 0;
        
